### ISSUE TITLE
Four test cases failing on rhel7.6 ppc64le

### ISSUE THREAD

**Issue by SantoshMagdum** [openresty/headers-more-nginx-module#103]
Hi All,

I had build the nginx binary on rhel 7.6 ppc64le (version 1.17.1.1rc0) from source code -  https://github.com/openresty/openresty.
Please note that, I had copied and used ppc64le compiled LuaJIT code while building openresty (nginx).
Below command I used to compile the openresty -
	

./configure --with-cc-opt="-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC" --with-http_image_filter_module --with-http_dav_module  --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_iconv_module  --with-http_drizzle_module --with-http_postgres_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module

And then tried to execute the test cases for 'headers-more-nginx-module' like below -

# pwd
/usr/openresty/openresty/openresty-1.17.1.1rc0/build/headers-more-nginx-module-0.33
# prove -r t/

NOTE: The 'headers-more-nginx-module' version downloaded from openresty bundle is 0.33

But I am getting below 4 test case failure (Here, I have pasted the uniq error messages but there are total of 4 error messages repeated which shows 4 test failures)-

	#   Failed test 'TEST 1: used output filter - pattern "headers more header filter" should match a line in error.log (req 1)'
	#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

Note - On the test report (for 22-Apr-2018, V1_11_2) these are shown as expected failures - http://openresty.org/download/test/linux_x86_64_nginx_1_11_2__no_pool__ngx_headers_more_o.html
But in latest report (ran on 16-May-2019, V1_15_8) these are not appearing.

Please help suggest if I need to export any specific environment or should try any compiler flag? Or is it OK to ignore these errors?

nginx version (compiled with libdrizzle 1.0 and radius, mariadb, postgresql services setup) -

	# nginx -V
	nginx version: openresty/1.17.1.1rc0
	built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
	built with OpenSSL 1.0.2k-fips  26 Jan 2017
	TLS SNI support enabled
	configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../drizzle-nginx-module-0.1.11 --add-module=../ngx_postgres-1.0 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_image_filter_module --with-http_dav_module --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module --with-stream --with-stream_ssl_preread_module

**Comment by agentzh** [comment]
That test case seems to rely on an openresty build with `./configure --with-debug`.

**Comment by SantoshMagdum** [comment]
@agentzh  - Thanks for the quick reply and suggestion.

With the use of "--with-debug" openresty compilation, these errors are disappeared now.

I would like to share same observation with "echo-nginx-module". Here also below error messages disappeared with above compilation change -
          #   Failed test 'TEST 14: unsafe uri - pattern "echo_location sees unsafe uri: "/../foo"" should match a line in error.log (req 0)'
