### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by khaiphan9x** [openresty/headers-more-nginx-module#106]
Its error
/usr/bin/ld: objs/addon/src/ngx_http_headers_more_util.o: in function `ngx_http_headers_more_parse_types':                          /tmp/build/openresty-1.15.8.2/../headers-more-nginx-module-master/src/ngx_http_headers_more_util.c:229: multiple definition of `ngx_http_headers_more_parse_types'; objs/addon/src/ngx_http_headers_more_util.o:/tmp/build/openresty-1.15.8.2/../headers-more-nginx-module-master/src/ngx_http_headers_more_util.c:229: first defined here/usr/bin/ld: objs/addon/src/ngx_http_headers_more_util.o: in function `ngx_http_headers_more_rm_header_helper':                     /tmp/build/openresty-1.15.8.2/../headers-more-nginx-module-master/src/ngx_http_headers_more_util.c:268: multiple definition of `ngx_http_headers_more_rm_header_helper'; objs/addon/src/ngx_http_headers_more_util.o:/tmp/build/openresty-1.15.8.2/../headers-more-nginx-module-master/src/ngx_http_headers_more_util.c:268: first defined here                                                             collect2: error: ld returned 1 exit status                        make[2]: *** [objs/Makefile:512: objs/nginx] Error 1              make[2]: Leaving directory '/tmp/build/openresty-1.15.8.2/build/nginx-1.15.8'                                                       make[1]: *** [Makefile:8: build] Error 2                          make[1]: Leaving directory '/tmp/build/openresty-1.15.8.2/build/nginx-1.15.8'                                                       make: *** [Makefile:9: all] Error 2

**Comment by agentzh** [comment]
@khaiphan9x OpenResty already ships with this headers more module. Why are you trying to add your own? That's why you are getting the error "multiple definition of ...", which clearly indicates duplications here.
