### ISSUE TITLE
Add Nginx 1.17.* Compatibility

### ISSUE THREAD

**Issue by entscheidungsproblem** [openresty/headers-more-nginx-module#113]
Can Nginx 1.17.* be added to the compatibility list?

**Comment by agentzh** [comment]
Oh yeah it has been tested with 1.17.8. We'll update the doc.

**Comment by agentzh** [comment]
Docs updated.

**Comment by entscheidungsproblem** [comment]
Sweet, thanks! 😄

**Comment by entscheidungsproblem** [comment]
Oh, could you add 1.18 as well? If 1.17.10 works, 1.18.0 will as well since there are functionally the same. [Here is the diff](https://github.com/nginx/nginx/compare/release-1.17.10...release-1.18.0)

**Comment by agentzh** [comment]
We need to test it first before we can do that.

**Comment by magic-thomas** [comment]
Isn't 1.18 tested yet?

**Comment by zhuizhuhaomeng** [comment]
openresty follow the odd number of nginx release.
