### ISSUE TITLE
Remove tag v0.261

### ISSUE THREAD

**Issue by jirutka** [openresty/headers-more-nginx-module#117]
Can you please remove tag v0.261? It’s a higher version than v0.33 and yet it’s much older. I’m using a script to detect the latest version and this anomaly is causing a lot of trouble to me.

**Comment by jirutka** [comment]
ping @agentzh @thibaultcha

**Comment by AliMD** [comment]
Please...
Its important
Add `v0.26.1` or `v0.26s1` instead

**Comment by xiaocang** [comment]
Hi @jirutka, @AliMD thanks for reporting, we'll remove the tag and it will just look like a typo

**Comment by xiaocang** [comment]
the tag `v0.261` has been removed
