### ISSUE TITLE
Repeated headers are occluded incorrectly

### ISSUE THREAD

**Issue by sevmonster** [openresty/headers-more-nginx-module#141]
For example, if your proxy returns a `Set-Cookie` header, and you attempt to add a new `Set-Cookie` header to the response, all the previous `Set-Cookie` headers will be lost. This functionality makes sense for headers that should only be specified once, but for multi-use headers like `Set-Cookie` the list should be appended instead of replaced. My particular use case for this was adding an upstream cookie after an [`auth_request`](https://nginx.org/r/auth_request).

If this is an intended feature as #18 suggests, maybe it should be added to the `README`.

**Comment by zhuizhuhaomeng** [comment]
I think add an append mode is a good choice.

**Comment by lynch1981** [comment]
I added this feature, please check out my patch when you have time. @zhuizhuhaomeng

**Comment by milas** [comment]
I see #151 was merged but limited to `Set-Cookie`. Since it's behind a new `-a` (append) flag, would you accept a PR to remove the `Set-Cookie` restriction and allow it for any header?

I'd like to use it with `X-Robots-Tag`, so I can target specific crawlers, which requires multiple headers. (See https://http.dev/x-robots-tag#targeting-specific-web-crawlers.)

**Comment by lynch1981** [comment]
Most headers cannot be repeated, so removing the Set-Cookie restriction is not a good idea. And we can't have a complete list of which headers can support repeated additions. So as agent said, it is recommended that you use the ngx_lua module to do this.

**Comment by zhuizhuhaomeng** [comment]
@lynch1981 @milas Removing the restriction is acceptable to me.
because removing the restriction won't break the backward compatibility.

It is the user's responsibility to choose the right option of more_set_headers.

**Comment by lynch1981** [comment]
@zhuizhuhaomeng @milas 
Let me fix this problem. There needs to be clear instructions in the readme file.

**Comment by lynch1981** [comment]
@zhuizhuhaomeng I think the behavior of built-in headers should not be changed, your opinion?

**Comment by zhuizhuhaomeng** [comment]
> @zhuizhuhaomeng I think the behavior of built-in headers should not be changed, your opinion?

**Comment by zhuizhuhaomeng** [comment]
I have reviewed the code.
We should return an error when -a option is on the built-in header.

**Comment by lynch1981** [comment]
Good idea, this makes it clearer and easier for users to use

**Comment by milas** [comment]
I believe this was resolved with #152 and v0.36, so this issue can likely be closed now. Thanks!

**Comment by sevmonster** [comment]
Thank you, I had forgotten to close this.
