### ISSUE TITLE
Wildcard support for more_clear_input_headers

### ISSUE THREAD

**Issue by davidjb** [openresty/headers-more-nginx-module#15]
It seems as though wildcards aren't supported for clearing request headers in `more_clear_input_headers` like they are for clearing response headers in `more_clear_headers`.

Could this be added as a feature?  Due to the way an authentication module (Shibboleth; works using headers) I need to use operates, only a wildcard (or regex) would help stop arbitrary headers with a certain prefix.

**Comment by vidiecan** [comment]
+1

**Comment by kosarko** [comment]
+1
