### ISSUE TITLE
Remove “Connection: keep-alive” response header in NGINX 204 response with HTTP/1.1

### ISSUE THREAD

**Issue by mikeaorlando** [openresty/headers-more-nginx-module#22]
When using

```
more_clear_headers 'Connection';
```

our response headers still contain the header and look like this:

```
HTTP/1.1 204 No Content
Connection: keep-alive
```

Is this expected behavior? We've tried a number of workarounds but it seems like it may be a bug. Thank you!

Full details: http://stackoverflow.com/questions/20919207/remove-connection-keep-alive-response-header-in-nginx-204-response-with-http

**Comment by amalakar** [comment]
Is there an update here, or recompiling nginx is still the only way to achieve this?

**Comment by agentzh** [comment]
@amalakar Your own patched or extended nginx is also broken here like @coreyauger's? What's the matter, really?

**Comment by agentzh** [comment]
@amalakar Replying to an already closed issue is also strange. Are you sure you are also using some broken "Play Framework chunked response" as mentioned by @coreyauger ?

**Comment by amalakar** [comment]
Hey @agentzh sorry for my confusing comment, I noticed that latest document mentions this explicitly - https://github.com/openresty/headers-more-nginx-module#limitations 

I stumbled upon this PR from 2014, and was not sure if the limitations still holds true or if latest version of nginx has this limitation removed. Looking at the nginx code I noticed that it is still holds true, only way I was able to remove the Connection header from nginx version `1.13.9` was to recompile nginx.

**Comment by qg0** [comment]
Here is an example patch for nginx source file: `src/http/ngx_http_header_filter_module.c:`
```
diff -r d2b2ff157da5 -r 25129d5509b8 src/http/ngx_http_header_filter_module.c
--- a/src/http/ngx_http_header_filter_module.c  Tue Jan 31 21:19:58 2017 +0300
+++ b/src/http/ngx_http_header_filter_module.c  Thu Feb 02 02:14:06 2017 +0800
@@ -389,7 +389,9 @@
         }

     } else {
-        len += sizeof("Connection: close" CRLF) - 1;
+        if (clcf->keepalive_header != 0) {
+            len += sizeof("Connection: close" CRLF) - 1;
+        }
     }

 #if (NGX_HTTP_GZIP)
@@ -560,8 +562,10 @@
         }

     } else {
-        b->last = ngx_cpymem(b->last, "Connection: close" CRLF,
-                             sizeof("Connection: close" CRLF) - 1);
+        if (clcf->keepalive_header != 0){
+             b->last = ngx_cpymem(b->last, "Connection: close" CRLF,
+                                  sizeof("Connection: close" CRLF) - 1);
+        }
     }

 #if (NGX_HTTP_GZIP)
```
