### ISSUE TITLE
Header output truncating?

### ISSUE THREAD

**Issue by kylegato** [openresty/headers-more-nginx-module#32]
Hello,

I am using more_set_headers to replace the Server: header response from "nginx" to show our internal server hostnames for tracking. I don't need to expose the full hostname so I strip the domain and grab the datacenter.

Hostname I am testing with: kyle.mdr.domain.com
NGINX Config Section: http block

```
    map $hostname $new_hostname {
      ~^(?<server_hostname>.*)\.(?<datacenter2>.*)\.(.*)\.com$ $server_hostname;
    }
    more_set_headers 'Server: WD ($new_hostname/$datacenter2)';
```
Returns: Server: WD (kyle/mdr)

```
    map $hostname $new_hostname {
      ~^(?<server_hostname>.*)\.(?<datacenter2>.*)\.(.*)\.com$ $server_hostname;
    }

    more_set_headers 'Server: WD ($datacenter2/$new_hostname)';
```

Returns: Server: WD (mdr/ky

I cannot figure out why it would truncate based on which variable appears first...

FreeBSD kyle.mdr.domain.com 10.0-RELEASE FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

```
nginx version: nginx/1.7.10
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx-error.log --user=www --group=www --with-file-aio --with-ipv6 --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx-access.log --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/nginx-accesskey-2.0.3 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx_http_auth_pam_module-1.2 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/openresty-headers-more-nginx-module-0c6e05d --with-http_gzip_static_module --with-http_gunzip_module --with-http_realip_module --with-http_secure_link_module --with-http_stub_status_module --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/nginx_upload_module-2.2.0 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/mod_zip-1.1.6 --with-pcre --with-http_spdy_module --with-http_ssl_module
```

**Comment by kylegato** [comment]
Even weirder, the following actually works:

```
    map $hostname $datacenter {
      ~^(?<server_hostname>.*)\.(?<datacenter2>.*)\.(.*)\.com$ $datacenter2;
    }

    more_set_headers 'Server: WD ($datacenter/$server_hostname)';
```
Returns: Server: WD (mdr/kyle)

**Comment by agentzh** [comment]
@kylegato Will you minimize your example without the `map` and those details? Better start with testing the simplest thing that could possibly work. Your detailed logic confuses me which should be irrelevant to the real problem you're having.

**Comment by agentzh** [comment]
@kylegato Okay, after having a closer look at your original code snippet, it's indeed your `map` directive being the culprit.

Please note that variables defined by `map` are evaluated *lazily* (or only upon the first reference). So in your 2nd example, the regex has not yet been matched until your first reference of the `$new_hostname` variable (which is defined by `map`). So when you reference the `$datacenter2` in your second example, the regex has not yet been evaluated and thus the named captured variable `$datacenter2` has not yet been initialized.

**Comment by agentzh** [comment]
Because this has nothing to do with ngx_headers_more (nor a bug in `map`), I'm closing this.
