### ISSUE TITLE
Question about module post configuration and handler function

### ISSUE THREAD

**Issue by avbagno** [openresty/headers-more-nginx-module#33]
Hi! 
I'm new to nginx and currently I'm studying using Your's modules.   
I would be really appreciate if you could explain me what next statements mean :

static ngx_int_t
ngx_http_headers_more_post_config(ngx_conf_t *cf)
{
...
    if (ngx_http_headers_more_prev_cycle != ngx_cycle) {
        ngx_http_headers_more_prev_cycle = ngx_cycle;
        multi_http_blocks = 0;

    } else {
        multi_http_blocks = 1;
    }  
 ph = cmcf->phase_engine.handlers;
....
}

static ngx_int_t
ngx_http_headers_more_handler(ngx_http_request_t *r)
{
....
if (!hmcf->postponed_to_phase_end) {
        ngx_http_core_main_conf_t       *cmcf;
        ngx_http_phase_handler_t         tmp;
        ngx_http_phase_handler_t        *ph;
        ngx_http_phase_handler_t        *cur_ph;
        ngx_http_phase_handler_t        *last_ph;

        hmcf->postponed_to_phase_end = 1;

        cmcf = ngx_http_get_module_main_conf(r, ngx_http_core_module);

        ph = cmcf->phase_engine.handlers;
        cur_ph = &ph[r->phase_handler];
        last_ph = &ph[cur_ph->next - 1];

        if (cur_ph < last_ph) {
            dd("swaping the contents of cur_ph and last_ph...");

            tmp = *cur_ph;

            memmove(cur_ph, cur_ph + 1,
                    (last_ph - cur_ph) * sizeof (ngx_http_phase_handler_t));

            *last_ph = tmp;

            r->phase_handler--; /* redo the current ph */

            return NGX_DECLINED;
        }
    }
  
...
}

Great thank for your work!

**Comment by agentzh** [comment]
@avbagno Sorry, I usually don't do such code explanation work for free. If you would like to pay me, try contacting privately via my personal email address, agentzh@gmail.com

Thank you :)
