### ISSUE TITLE
Set headers on 401 fails.

### ISSUE THREAD

**Issue by istr** [openresty/headers-more-nginx-module#34]
I seem to be unable to set a header on 401 responses, e.g.

```
server {
...
# enable HSTS, timeout 365 days
more_set_headers 'Strict-Transport-Security: max-age=31536000';
# deny in-frame delivery
more_set_headers 'X-Frame-Options: DENY';
...
}
```

Is this the same issue like #26 ("early" / "late") status or is it something else?
Headers are set on any location correctly, but not on 401 / Basic Auth, effectively breaking HSTS.

**Comment by agentzh** [comment]
@istr Will you provide a standalone and minimal example that can easily reproduce this on my side? (Please note that your previous sample is incomplete, because there is no info regarding how to generate the 401 response nor info on your test requests). Thank you!

**Comment by istr** [comment]
Outdated.
