### ISSUE TITLE
type will not match `text/html; charset=utf-8`

### ISSUE THREAD

**Issue by joebartels** [openresty/headers-more-nginx-module#38]
I am trying to use `more_set_headers` inside a server or location block that reverse proxies to an upstream server
```nginx
server { 
  listen 80;
  listen 443 ssl;
  server_name somesite.com;

  # more_set_headers -t 'text/html' 'X-Test: foo';                  # doesn't work
  # more_set_headers -t 'text/html; charset=utf-8' 'X-Test: foo';   # doesn't work
  # more_set_headers -s '200' 'X-Test: foo';                        # works
  # more_set_headers 'X-Test: foo';                                 # works

  location / {
    proxy_pass http://upstream_server;
  }
}
```

The response coming from the `upstream_server` has `Content-Type: text/html; charset=utf-8`

I am use nginx 1.8.0 which I know isn't on the list of "supported" versions. Any thoughts?

**Comment by agentzh** [comment]
@joebartels Yeah, nginx 1.8.0 should work.

Thank you for the report. I'll try reproducing it on my side and look into it.

**Comment by agentzh** [comment]
@joebartels I've committed a fix to git master that should fix this problem. Thank you for the report. BTW, it's wrong to use suffixes like "; charset=utf-8" in the `-t` options. I've made it clear in the documentation.

Thanks again!

**Comment by joebartels** [comment]
@agentzh terrific! Just tried it out -worked as expected. Thanks

**Comment by agentzh** [comment]
@joebartels Good to know. Thank you for the feedback!
