### ISSUE TITLE
Dynamic loadable

### ISSUE THREAD

**Issue by sbagmeijer** [openresty/headers-more-nginx-module#43]
If possible could you support this module so it can be dynamic loadable as is possible in nginx 1.9.11?

https://www.nginx.com/resources/wiki/extending/converting/
https://www.nginx.com/resources/wiki/extending/new_config/#

**Comment by sbagmeijer** [comment]
I added a fix to the config file that worked for me hope it helps you! :)

**Comment by agentzh** [comment]
Working in master now.
