### ISSUE TITLE
Is it possible to use this module to strip google analytics cookies?

### ISSUE THREAD

**Issue by deweydb** [openresty/headers-more-nginx-module#45]
If so can anyone provide an example of the correct syntax?  Ideally i would like to strip the _ga and _gat cookies sent from the client before they reach my upstream, but leave all other cookies intact.

**Comment by agentzh** [comment]
@deweydb I don't think so. For such more complicated task, you'd better use the ngx_http_lua_module instead:

https://github.com/openresty/lua-nginx-module

**Comment by deweydb** [comment]
Actually it turns out to be really really simple. Lua seems to be total overkill.

Here is an example for anyone else who finds this wanting to do the same thing.

`
    # strip all google analytics cookies before they head upstream
    # this is because drupal needs to use the header: vary: cookie;
    # and we still want caching to work.
    set $new_cookie $http_cookie;
    if ($http_cookie ~ "(.*)(?:^|;)\s*discourse_logged_in=[^;]+(.*)$") {
       set $new_cookie $1$2;
    } 
    if ($new_cookie ~ "(.*)(?:^|;)\s*_ga=[^;]+(.*)$") {
       set $new_cookie $1$2;
    }
    if ($new_cookie ~ "(.*)(?:^|;)\s*_gat=[^;]+(.*)$") {
       set $new_cookie $1$2;
    }
    more_set_input_headers 'Cookie: $new_cookie';
`

**Comment by agentzh** [comment]
@deweydb "If is evil" :)

https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by deweydb** [comment]
Ehhhhh.... i think you are misunderstanding that article and there reason for the title.  If is not always evil.  And if is incredibly useful, and performant.

Giving a blanket statement that all if statements in nginx are wrong is simply incorrect.

And suggesting to use an entirely separate module and scripting language instead of just using one if statement is a bit absurd.

**Comment by agentzh** [comment]
That was just a friendly reminder. Your response is an excellent way to ask for help. BTW, I also contributed to that article and even patches to make "if" a little bit better.
