### ISSUE TITLE
headers-more-nginx-module is not support DSO？ 

### ISSUE THREAD

**Issue by Michael754267513** [openresty/headers-more-nginx-module#46]
headers-more-nginx-module is not support DSO？   tengine version 2.1.2 ，

**Comment by agentzh** [comment]
@Michael754267513 This modules supports being compiled as a DSO with the official NGINX 1.9.11+ distributions on the git master. Tengine, as an NGINX fork, has never been an officially supported target of this module BTW.

**Comment by Michael754267513** [comment]
@agentzh alright，ｉcompile tengine agent and add module of this module，i want to test varnish and tengine ,so i need  to custom head for this module!
