### ISSUE TITLE
unknown directive "more_clear_headers"

### ISSUE THREAD

**Issue by pulakivasilaki** [openresty/headers-more-nginx-module#54]
freebsd 10.3 amd64

nginx -V
nginx version: nginx/1.10.0
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --modules-path=/usr/local/etc/nginx/modules --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx-error.log --user=www --group=www --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx-access.log --with-http_addition_module --with-http_auth_request_module --add-dynamic-module=/usr/ports/www/nginx/work/headers-more-nginx-module-f5559ec --with-http_gzip_static_module --with-http_gunzip_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_stub_status_module --with-http_sub_module --with-pcre --with-http_v2_module --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-mail_ssl_module --with-http_ssl_module

Performing sanity check on nginx configuration:
nginx: [emerg] unknown directive "more_clear_headers" in /usr/local/etc/nginx/nginx.conf:25

**Comment by agentzh** [comment]
@pulakivasilaki It's very likely you are using the wrong nginx binary in your nginx startup script? The `PATH` environment might be different in that context.

**Comment by intchloe** [comment]
Have we verified that more_headers-module actually works with the nginx 1.10-branch?

**Comment by agentzh** [comment]
@intchloe Yes. See:

https://travis-ci.org/openresty/headers-more-nginx-module

**Comment by jfromaniello** [comment]
I am having the same problem with this version of nginx:

```
$ nginx -V
nginx version: nginx/1.11.5
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/headers-more-nginx-module --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-auth-pam --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-cache-purge --add-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-dav-ext-module --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-development-kit --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-echo --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/ngx-fancyindex --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nchan --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-lua --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-upload-progress --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/nginx-upstream-fair --add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/ngx_http_substitutions_filter_module
```

I am running on ubuntu and I used the apt package named `nginx-extras`. I am quite sure there isn't any other nginx in the box:

```
$ which nginx
/usr/sbin/nginx

$ cat /etc/init.d/nginx  | grep 'DAEMON='
DAEMON=/usr/sbin/nginx
```

**Comment by jfromaniello** [comment]
works with an older version:
```
sudo apt-get install nginx-extras=1.4.6-1ubuntu3.7 nginx-common=1.4.6-1ubuntu3.7
```

**Comment by agentzh** [comment]
@jfromaniello It seems that you are building this ngx_headers_more module as a *dynamic module*, which means that it's your responsibility now to load the ngx_headers_more module explicitly via the `load_module` directive in your `nginx.conf` file. See the relevant documentation:

https://github.com/openresty/headers-more-nginx-module/#installation

**Comment by agentzh** [comment]
@jfromaniello Note the use of the `--add-dynamic-module=PATH` option in your `nginx -V` output:

`--add-dynamic-module=/build/nginx-CWg6sX/nginx-1.11.5/debian/modules/headers-more-nginx-module`

**Comment by agentzh** [comment]
@jfromaniello Such issues should really be reported to the maintainers of the Debian binary package you are using instead of here.

**Comment by reportingforduty** [comment]
Damn. I've experienced this issue today.

@jfromaniello Hey dude. Email to these maintainers with this github URL.

https://packages.debian.org/stretch/nginx-extras

**Comment by reportingforduty** [comment]
20-6=14. 2 weeks and no one cares about this issue? WTF Debian.

**Comment by sztricskoj** [comment]
Did you have nginx.conf configuration directive like this?
include /etc/nginx/modules-enabled/*.conf;

**Comment by agentzh** [comment]
@reportingforduty You were not watching. You are reporting issues to the wrong place. See all the discussions above more carefully. There is nothing we can do on our side. So please be nice here.
