### ISSUE TITLE
Compiling dynamic module

### ISSUE THREAD

**Issue by egorsmkv** [openresty/headers-more-nginx-module#55]
I'm trying to compile the module, but in the second step, get the following error.

```
root@machine:~/build/nginx-1.10.0# make modules 
make -f objs/Makefile modules
make[1]: Entering directory '/root/build/nginx-1.10.0'
make[1]: Nothing to be done for 'modules'.
make[1]: Leaving directory '/root/build/nginx-1.10.0'
```

First step:

```
root@machine:~/build/nginx-1.10.0# ./configure --add-dynamic-module=../headers-more-nginx-module-0.29

...
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional dynamic modules
adding module in ../headers-more-nginx-module-0.29
 + ngx_http_headers_more_filter_module was configured
checking for PCRE library ... found
checking for PCRE JIT support ... found
checking for md5 in system md library ... not found
checking for md5 in system md5 library ... not found
checking for md5 in system OpenSSL crypto library ... found
checking for sha1 in system md library ... not found
checking for sha1 in system OpenSSL crypto library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + OpenSSL library is not used
  + md5: using system crypto library
  + sha1: using system crypto library
  + using system zlib library
...
```

After the usual `make` library in `objs` folder does not appear.

**Comment by agentzh** [comment]
@egorsmkv I didn't see any errors in the output of your `make modules` command.

And I've tried nginx 1.10.0 on my side and it works for me:

```console
$ ls objs|grep .so
ngx_http_headers_more_filter_module.so*
```

**Comment by egorsmkv** [comment]
@agentzh No, files do not appear.

I'm trying to assemble a module on Debian. What third party libraries I need to install?

**Comment by agentzh** [comment]
@egorsmkv You can paste the full output of the commands `./configure ...` and `make` and `ls` somewhere like on gist. And share the link here. I guess you are just making some basic mistake in your procedure.

No, no 3rd-party libraries needed to build this module.

**Comment by egorsmkv** [comment]
@agentzh https://gist.github.com/egorsmkv/3c8f71f7c2fa0c31fba20710b153469c

**Comment by agentzh** [comment]
@egorsmkv Okay, I see. You're using an older version of ngx_headers_more, v0.29, which does not support being compiled as an nginx dynamic module at all. You need at least v0.30rc1 or the latest git master branch of the repository.
