### ISSUE TITLE
Clear nginx header variables

### ISSUE THREAD

**Issue by davidjb** [openresty/headers-more-nginx-module#62]
On testing out #61, I noticed the following still has the header value present:
```
    location / {
       more_clear_input_headers 'Remote-User';
       return 200 $http_remote_user;
    }
```
This was a little confusing as the value was still present in the variable.

I'm thinking that (if possible) the nginx variables (eg `$http_*` and `$upstream_http_*`) set for request/response headers should be unset by `more_clear_input_headers` / `more_clear_headers`.  Alternatively, a more flexible solution could be to add a toggle for this behaviour in case someone wants the header cleared from a request/response but still wants to use the header in their configuration, such as logging, if statements etc.

**Comment by agentzh** [comment]
@davidjb You know that the `return` directive always runs before `more_clear_input_headers` regardless of their order in the nginx.conf?

**Comment by agentzh** [comment]
@davidjb You can try the `echo` directive instead of `return` in your example, as in

```nginx
    location / {
       more_clear_input_headers 'Remote-User';
       echo $http_remote_user;
    }
```

This runs in the expected order since `echo` is a content handler.

Always pay special attention to nginx directives' running order.

**Comment by davidjb** [comment]
Okay, thanks @agentzh that makes sense.  I've made a small doc update at #63 to help explain.

Are there any resources than that explain what type of handler each directive is associated with?  There's http://www.nginxguts.com/2011/01/phases/ which is comprehensive in covering the phases; perhaps the best option is to read nginx's source.

Closing as this is working as expected.
