### ISSUE TITLE
Windows版本如何添加more_set_headers和more_clear_headers模块

### ISSUE THREAD

**Issue by X-rapido** [openresty/headers-more-nginx-module#67]
您好，请问一下，Windows服务器的Nginx，该怎么添加和修改more_set_headers和more_clear_headers模块呢？ 我查阅了一些资料都为Linux中的安装配置，可是目前公司的服务器是WIndows，请问您有什么解决思路或办法吗？ 谢谢

**Comment by agentzh** [comment]
No Chinese allowed here. Thank you.

**Comment by agentzh** [comment]
Regarding your question, OpenResty provides official binary package for Windows, which includes this headers more module. Please check it out on openresty.org. Thank you.

**Comment by X-rapido** [comment]
Sorry , My english is pool，Thank you answer the question， I can find the binary package，  https://github.com/openresty/headers-more-nginx-module，But，The document only describes the linux installation，My nginx in the window environment is free to install version 1.11.3， I really don't know how to use it ，I'm a student，please help guide, very grateful, I'm very grateful for thank you very much

**Comment by agentzh** [comment]
See https://openresty.org/en/download.html

**Comment by lysgwl** [comment]
> No Chinese text allowed here. Thank you.

你是二笔代表吧，中文招惹你啦。
