### ISSUE TITLE
load module error

### ISSUE THREAD

**Issue by MisterChing** [openresty/headers-more-nginx-module#73]
ngx_http_headers_more_filter_module.so is is not binary compatible in /home/ching/env/server/nginx/./conf/nginx.conf:11

**Comment by agentzh** [comment]
@MisterChing It seems that ngx_http_headers_more_filter_module.so was not generated with the nginx binary you are using. You are just invoking the wrong nginx binary.

**Comment by ArupKantiDas** [comment]
How to generate ngx_http_headers_more_filter_module.so using the nginx binary that was install earlier using yum install nginx.
