### ISSUE TITLE
Any way to install this without installing nginx from source?

### ISSUE THREAD

**Issue by pkiula** [openresty/headers-more-nginx-module#74]
For pragmatic reasons, on our production environment, we have the 1.10.3 version of nginx installed by `yum`. Is there any way to install this additional module without re-installing nginx from the core source files all over again? Thank you.

**Comment by draskolnikova** [comment]
@pkiula IMHO is not possible right now, nginx said that even core module that not enable by default, should be enable and build using parameter `--with`, then 3rd-party module using parameter `--add-module`

Tips:
If you have issue to keep your environment clean, try to rebuild your nginx and make it as `.rpm` files.

**Comment by sergey-dryabzhinsky** [comment]
If your `yum` version of nginx don't have this module compiled-in then you can compile with module as dynamicaly loaded.

1. Get sources of your nginx version.
2. Compile module as dynamic via configure option `--add-dynamic-module=/path/to/module/sources`
3. Don't install compiled nginx, just put compiled module binary into, well, `/usr/lib/nginx/modules/`. And then in nginx configs set `load_module /full/path/to/module/binady.so`

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by agentzh** [comment]
@sergey-dryabzhinsky Using the original nginx source is not enough, one also has to make sure he uses the exactly the same `./configure` options as the original binary build.

**Comment by sergey-dryabzhinsky** [comment]
@agentzh Totally agree.
