### ISSUE TITLE
Question on documentation / add_headers constraint Expires, Cache-Control, ...

### ISSUE THREAD

**Issue by c0d3z3r0** [openresty/headers-more-nginx-module#77]
Could you explain what is meant by "... this module does not automatically take care of the constraint among the Expires, Cache-Control, and Last-Modified headers ...", please?
Thanks!

**Comment by agentzh** [comment]
@c0d3z3r0 It just means when you use this module to change the `Expires` header value, this module won't automatically update the `Cache-Control` header. The same applies to other similar situations.
