### ISSUE TITLE
Append header without overwriting

### ISSUE THREAD

**Issue by vincentbernat** [openresty/headers-more-nginx-module#78]
Hey!

For some headers, a user may want to append an extra copy of the header instead of replacing it altogether. For example, this would be useful for the `Vary` header. Setting it should just result in appending a new copy of this header, leaving the previous one intact.

**Comment by agentzh** [comment]
@vincentbernat Why don't you just use nginx's standard `add_header` directive? See

http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

**Comment by vincentbernat** [comment]
Because of the absence of inheritance. It's easy to discard an unerelated `add_header` that was set at a upper level.

**Comment by agentzh** [comment]
Then you should ask the nginx team to address it instead of asking us to duplicate the code in this 3rd-party module. This issue is closed.

**Comment by fuweichin** [comment]
Due to "the absence of inheritance", `add_header` is so ungelivable, but thanks to `more_add_headers`, I solved the problem, here is how:

```nginx
# define varialble $comma_vary
map $sent_http_vary $comma_vary {
  default "";
  ~.+ ",$sent_http_vary";
}

server {
  # ...
  location / {
    proxy_pass http://localhost:8080;
    if ($http_access_control_request_method != "") {
      # ...
      more_set_headers "vary: origin,access-control-request-method,access-control-request-headers$comma_vary";
      return 204;
    }
    if ($http_origin != "") {
      # ...
      more_set_headers "vary: origin$comma_vary";
    }
  }
}
```

while this task can be done more easily with a directive like `more_add_headers`.

**Comment by fuweichin** [comment]
mistyping
