### ISSUE TITLE
compatibility problems (with same binary)

### ISSUE THREAD

**Issue by tarreislam** [openresty/headers-more-nginx-module#83]
Hello!

Im getting this, and I cannot understand why.

`nginx: [emerg] module "/....../ngx_http_headers_more_filter_module.so" is not binary compatible`

This is how i created the binary.

1. Download and unzip `http://nginx.org/download/nginx-1.10.3.tar.gz` (nginx -v = `1.10.3` )
2. `./configure --prefix=/home/xxx/nginx --add-dynamic-module=/home/xxx/headers-more-nginx-module-0.33`
3. `make modules`
4. `cp /../objs/ngx_http_headers_more_filter_module.so /etc/nginx/modules`
5. `nginx -s reload`

Then copied `ngx_http_headers_more_filter_module.so` to `/etc/nginx/modules`

**Comment by tarreislam** [comment]
I got the same error when i did `make` + `make install`

**Comment by agentzh** [comment]
@tarreislam You should use the same binary nginx (or binary compatible ones) that you used to build this module. The "not binary compatible" error message is already clear enough about the problem.

**Comment by agentzh** [comment]
@tarreislam Use the absolute path to your nginx binary to make sure you are not fooled by varying `PATH` environment settings in your own system.
