### ISSUE TITLE
nginx-1.13.10下编译headers-more-nginx-module出错(付错误报告)

### ISSUE THREAD

**Issue by ClayMoreBoy** [openresty/headers-more-nginx-module#85]
兼容性问题吗
**编译参数**
nginx version: nginx/1.13.10
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-zlib=../zlib **--with-openssl=../openssl-1.1.1-pre3** --with-openssl-opt='enable-tls1_3 zlib' --with-pcre=../pcre-8.42 --with-pcre-jit --with-ld-opt='-ljemalloc -Wl,-rpath,/usr/local/lib' --with-http_v2_hpack_enc --add-module=../ngx_devel_kit --add-module=../lua-nginx-module --add-module=../iconv-nginx-module --add-module=../echo-nginx-module --add-module=../xss-nginx-module --add-module=../ngx_coolkit --add-module=../set-misc-nginx-module --add-module=../form-input-nginx-module --add-module=../encrypted-session-nginx-module --add-module=../srcache-nginx-module --add-module=../lua-upstream-nginx-module --add-module=../headers-more-nginx-module --add-module=../array-var-nginx-module --add-module=../memc-nginx-module --add-module=../redis2-nginx-module --add-module=../rds-json-nginx-module --add-module=../rds-csv-nginx-module --add-module=../ngx_brotli --add-module=../nginx-ct --add-module=../incubator-pagespeed-ngx-1.13.35.2-stable --add-module=../ngx_cache_purge  **--add-module=../headers-more-nginx-module**

错误提示
objs/addon/src/ngx_http_headers_more_headers_in.o:ngx_http_headers_more_headers_in.c:(.text+0xcaf): first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_header':
ngx_http_headers_more_util.c:(.text+0x0): multiple definition of `ngx_http_headers_more_parse_header'
objs/addon/src/ngx_http_headers_more_util.o:ngx_http_headers_more_util.c:(.text+0x0): first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_statuses':
ngx_http_headers_more_util.c:(.text+0x362): multiple definition of `ngx_http_headers_more_parse_statuses'
objs/addon/src/ngx_http_headers_more_util.o:ngx_http_headers_more_util.c:(.text+0x362): first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_types':
ngx_http_headers_more_util.c:(.text+0x4e4): multiple definition of `ngx_http_headers_more_parse_types'
objs/addon/src/ngx_http_headers_more_util.o:ngx_http_headers_more_util.c:(.text+0x4e4): first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_rm_header_helper':
ngx_http_headers_more_util.c:(.text+0x599): multiple definition of `ngx_http_headers_more_rm_header_helper'
objs/addon/src/ngx_http_headers_more_util.o:ngx_http_headers_more_util.c:(.text+0x599): first defined here
**collect2: error: ld returned 1 exit status**
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/lnmp/src/nginx-1.13.10'
make: *** [build] Error 2
Nginx install failed, Please Contact the author!

**Comment by agentzh** [comment]
@ClayMoreBoy Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding to your error, it's your silly mistake to specify the `--add-module=../headers-more-nginx-module` option twice in your `./configure` command, hence the signature "multiple definition" compilation error. Next time please google for your error message before posting a FAQ to this place. Thank you.
