### ISSUE TITLE
How to install as a module WITHOUT recompile Nginx from source

### ISSUE THREAD

**Issue by pkiula** [openresty/headers-more-nginx-module#86]
Hello. CentOS 7, Nginx was installed via `yum install nginx`. Sadly, this installs Nginx 1.12.2. And there's no way to install any "http more headers" or this module in a YUM way. So I'd like to know if there's a way to install this module as a "dynamic module" for which I don't need to recompile Nginx from source etc? I'd like to run Nginx as a service, which is what it does today with Yum version. Thanks.

**Comment by LovelyA72** [comment]
try OpenResty instead. It have this module built in(since this module was made by them) and also have sth else pretty cool and i believe you will need later.

**Comment by agentzh** [comment]
@pkiula Read the documentation:

https://openresty.org/en/download.html

https://openresty.org/en/linux-packages.html

https://openresty.org/en/rpm-packages.html

**Comment by pkiula** [comment]
Thank you. But this is not a good solution for us. We'd like to use core Nginx, thanks for the recommendation.

**Comment by zds-d** [comment]
nginx-plus can，But that's the commercial version
[https://docs.nginx.com/nginx/admin-guide/dynamic-modules/headers-more/](https://docs.nginx.com/nginx/admin-guide/dynamic-modules/headers-more/)
[https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-plus/#install_rhel_centos](https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-plus/#install_rhel_centos)
