### ISSUE TITLE
Headers get cleared when leaving scope

### ISSUE THREAD

**Issue by niklasR** [openresty/headers-more-nginx-module#93]
Given the following config, the `X-Example-Header` does not get set when the proxy_pass returns a status code `500`:

```
http {
  more_clear_headers server;

  server {
    listen 7080;

    location / {
      more_set_headers 'X-Example-Header: openresty';
      proxy_pass https://internal.api.local;
      recursive_error_pages on;
      proxy_intercept_errors on;
      error_page 500 = @error;
    }

    location @error {
      return 500 '{ "status": ${status}, "reason": "Internal Server Error" }';
    }
  }
}
```

The docs do not mention this case. Is that by design? If so, should it be in the docs more clearly?

**Comment by agentzh** [comment]
@niklasR Nginx configuration directive is only effective in the scope it is used. It applies to all directives in all nginx modules. So I don't think every nginx module should document this for all its directives...It's really universal behavior defined by the nginx core, not us.
