### ISSUE TITLE
Does headers-more-nginx-module 0.33 support nginx 1.14.2?

### ISSUE THREAD

**Issue by 849511441** [openresty/headers-more-nginx-module#95]
Does headers-more-nginx-module 0.33 support nginx 1.14.2? Nginx 1.14.2 has been recompiled and SBIN has been replaced. The conf configuration file has also been modified and restarted, but it has no effect.

**Comment by 849511441** [comment]
location  /  
{      
                #     root  /home/wwwroot/default;
	 index index.html index.htm index.php;
	more_clear_headers X-Powered-By Server; # without effect ！

      if (!-e $request_filename) 
{
	rewrite  ^/(.*)$  /index.php?s=$1 last;
}

   }

**Comment by 849511441** [comment]
nginx version: nginx/1.14.2
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
built with OpenSSL 1.0.2l  25 May 2017
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-ipv6 --with-http_sub_module --with-openssl=/lnmp1.4/src/openssl-1.0.2l --add-module=/lnmp1.4/headers-more-nginx-module-0.33

**Comment by AliMD** [comment]
Yes of course, but need to compile with nginx 1.14.2
It may help, [best way to build](https://github.com/anroe/docker-nginx-headers-more/blob/master/alpine/Dockerfile)
